server:
  servlet:
    context-path: /auth
  port: 20000

spring:
  datasource:
    url: jdbc:mysql://192.168.10.58:3306/kinson?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: iris2003
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.15.160
    password: iris@2003
    timeout: 8000
    port: 6379
jasypt:
  encryptor:
    password: abc123