# 多环境通用部分[各个环境可以覆盖通用字段]
spring: 
  application:
    # 通用名字,其他环境可以覆盖：为你的应用起个名字，该名字将注册到eureka注册中心
    name: config-server
  #profiles: 
  #  active: subversion #使用SVN作为配置中心时使用
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lijinsheng90/springconfig.git
          searchPaths: config-repo
          username: 772995929@qq.com
          password: li7765287
      label: master
          #default-label: master
          #searchPaths: '{application}' #使用应用名称作为搜索路径 
          
#         svn:
#            uri: svn://localhost/demo/spring_cloud/parent/trunk/properties/
#            username: 你的SVN账号
#            password: 你的SVN密码
#            search-paths: '{application}'
#            default-label: trunk
server: 
  # 服务提供监听端口[eureka客户端],注意改端口不能与本机服务器端口冲突
  port: 8085
  
eureka:
  client:
    service-url:
       # 这里可以填写所有的eureka服务器地址并以','分离，当前面不能注册时候,自动选择后面的进行注册，排除单点故障问题
       defaultZone: http://localhost:8761/eureka/
       